name: Build & Deploy with Vite

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build with Vite
        run: npm run build
      - name: Deploy to o2switch via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.O2SWITCH_FTP_HOST }}
          username: ${{ secrets.O2SWITCH_FTP_USER }}
          password: ${{ secrets.O2SWITCH_FTP_PASSWORD }}
          local-dir: ./dist       # Vite génère ./dist par défaut
          server-dir: /cbleu.re